# Generated by Django 3.2.2 on 2021-05-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='data',
            new_name='date',
        ),
    ]
